services:
  db:
    image: postgres:16-alpine
    container_name: petronix_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: adminsecret
      POSTGRES_DB: petronix_db
    ports:
      - "5432:5432"
    volumes:
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: petronix_backend
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:adminsecret@db:5432/petronix_db"
      PORT: 3001
    ports:
      - "3001:3001"
    volumes:
      - ./uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: petronix_frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: "http://backend:3001/api"
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/public/img/products

volumes:
  postgres_data:
