services:
  db:
    image: postgres:16-alpine
    container_name: Petronix_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: adminsecret
      POSTGRES_DB: Petronix_db
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: Petronix_app
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:adminsecret@db:5432/Petronix_db"
      TELEGRAM_BOT_TOKEN: "8591029476:AAEGZBysaWCgrzyZNwAdFi8wl4Q9kEFl1Pk"
      TELEGRAM_CHAT_ID: "-4912475701"
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:adminsecret@postgres:5432/Petronix_db"
      TELEGRAM_BOT_TOKEN: "8591029476:AAEGZBysaWCgrzyZNwAdFi8wl4Q9kEFl1Pk"
      TELEGRAM_CHAT_ID: "-4912475701"
      NEXT_PUBLIC_ADMIN_USER_NAME: "Petronix_admin"
    command: sh -c "npm install && npx prisma generate && npx prisma migrate deploy && npm run build && npm run start"
    depends_on:
      - postgres

volumes:
  postgres_data:
